name: Build & Test (always) → Publish (tags only)

# Trigger on pushes to main (for testing) and tag pushes (for publishing)
on:
  push:
    branches:
      - main
    tags:
      - "v*" # build & push only when a tag is pushed (e.g. v1.2.3)
  workflow_dispatch: # allow manual runs (optional)

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # results in ghcr.io/owner/repo
  CONTAINERFILE: ./Containerfile

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
  # if you later add a release-update step, you'll need 'contents: write' or a PAT

jobs:
  # First run the CI tests
  test:
    uses: ./.github/workflows/ci.yml

  build-and-test:
    runs-on: ubuntu-latest
    needs: test
    # Always run this job for build testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Optional but recommended for multi-arch
      # - name: Set up QEMU (emulation for other archs)
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get git revision
        id: git
        run: |
          echo "revision=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Generate build string
        id: buildinfo
        run: |
          build_time=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
          short_sha=$(git rev-parse --short HEAD)
          echo "build_time=${build_time}" >> $GITHUB_OUTPUT
          echo "short_sha=${short_sha}" >> $GITHUB_OUTPUT
          echo "build_string=${build_time}-${short_sha}" >> $GITHUB_OUTPUT

      # Always build for testing (don't push unless it's a tag)
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.CONTAINERFILE }}
          push: false  # Never push from this job
          tags: test-build:latest
          build-args: |
            GIT_REVISION=${{ steps.git.outputs.revision }}
            BUILD_STRING=${{ steps.buildinfo.outputs.build_string }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    # Only run this job when a tag is pushed
    if: github.ref_type == 'tag'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Optional but recommended for multi-arch
      # - name: Set up QEMU (emulation for other archs)
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag           # will include the git tag (vX.Y.Z)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=sha-        # fallback: sha-abcdef
          # labels also generated (OCIs common labels)

      - name: Get git revision
        id: git
        run: |
          echo "revision=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Generate build string
        id: buildinfo
        run: |
          build_time=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
          short_sha=$(git rev-parse --short HEAD)
          echo "build_time=${build_time}" >> $GITHUB_OUTPUT
          echo "short_sha=${short_sha}" >> $GITHUB_OUTPUT
          echo "build_string=${build_time}-${short_sha}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (multi-arch)
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.CONTAINERFILE }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_REVISION=${{ steps.git.outputs.revision }}
            BUILD_STRING=${{ steps.buildinfo.outputs.build_string }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Generate build attestation (provenance)
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true

      - name: Create Markdown build summary (job summary)
        id: write-summary
        run: |
          # Compose summary variables
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          TAGS="${{ steps.meta.outputs.tags }}"
          DIGEST="${{ steps.build-and-push.outputs.digest }}"
          BUILD_TIME="${{ steps.buildinfo.outputs.build_time }}"
          GIT_REVISION="${{ steps.git.outputs.revision }}"
          BUILD_STRING="${{ steps.buildinfo.outputs.build_string }}"
          LABELS="${{ steps.meta.outputs.labels }}"

          # Create the markdown content once
          cat > build-summary.md <<EOF
          ## :package: Container publish summary

          | Property | Value |
          |----------|-------|
          | **Image** | \`${IMAGE}\` |
          | **Tags pushed** | \`${TAGS}\` |
          | **Floating tag (alias)** | \`${IMAGE}:latest\` |
          | **Digest** | \`${DIGEST}\` |
          | **Built at (UTC)** | \`${BUILD_TIME}\` |
          | **Commit** | \`${GIT_REVISION}\` |
          | **Build string** | \`${BUILD_STRING}\` |

          ### Labels (generated)
          \`\`\`
          ${LABELS}
          \`\`\`
          EOF

          # Copy the same content to the GitHub step summary
          cat build-summary.md >> $GITHUB_STEP_SUMMARY

      - name: Upload summary as artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: container-publish-summary
          path: build-summary.md
