name: CI Tests

on:
  workflow_call:

env:
  FRESH_PORT: 8000
  SERVER_TIMEOUT: 30
  HEALTH_PATH: /
  BUILD_CMD: deno run -A dev.ts build
  SERVE_CMD: deno serve -A _fresh/server.js
  TEST_CMD: deno task test:e2e

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type-check
        run: deno check **/*.ts **/*.tsx

      - name: Cache dependencies
        run: deno cache dev.ts

      - name: Build project
        run: ${{ env.BUILD_CMD }}

      - name: Start Fresh server in background
        run: ${{ env.SERVE_CMD }} &

      - name: Wait for server to be ready
        run: |
          timeout ${{ env.SERVER_TIMEOUT }} bash -c 'until curl -s http://localhost:${{ env.FRESH_PORT }}${{ env.HEALTH_PATH }} > /dev/null; do sleep 1; done'
          echo "Server is ready"

      - name: Run E2E tests
        run: ${{ env.TEST_CMD }}

      - name: Stop server
        run: pkill -f "deno" || true
